### LOCAL

### Get the message: Hello World!
GET http://localhost:3000/

### Get all the contacts
GET http://localhost:3000/contacts

### Get contact by ID
GET http://localhost:3000/contacts/68cd94b356eb35fd1106f9fc

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Gabriel",
    "lastName": "Rodríguez",
    "email": "gabriel.rodriguez@email.com",
    "favoriteColor": "Gris",
    "birthday": "1999-10-30"
}

### RENDER

### Get the message: Hello World!
GET https://cse-341-project1-7a6g.onrender.com

### Get all the contacts
GET https://cse-341-project1-7a6g.onrender.com/contacts

### Get contact by ID
GET https://cse-341-project1-7a6g.onrender.com/contacts/66feda6634acaf25fc843242
