### LOCAL

### Get the message: Hello World!
GET http://localhost:3000/

### Get all the contacts
GET http://localhost:3000/contacts

### Get contact by ID
GET http://localhost:3000/contacts/66feda6634acaf25fc843242

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "email": "test4@test.com",
  "contactname": "test4@test.com",
  "name": "Hello4",
  "ipaddress": "94.121.16.56"
}

### RENDER

### Get the message: Hello World!
GET https://cse-341-project1-7a6g.onrender.com

### Get all the contacts
GET https://cse-341-project1-7a6g.onrender.com/contacts

### Get contact by ID
GET https://cse-341-project1-7a6g.onrender.com/contacts/66feda6634acaf25fc843242
